# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: master_server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='master_server.proto',
  package='master_server',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13master_server.proto\x12\rmaster_server\"\x1a\n\nSensorName\x12\x0c\n\x04name\x18\x01 \x01(\t\"\\\n\nSensorData\x12\x11\n\ttimestamp\x18\x01 \x01(\x05\x12\x12\n\nrow_number\x18\x02 \x01(\x05\x12\x12\n\ncol_number\x18\x03 \x01(\x05\x12\x13\n\x0bsensor_data\x18\x04 \x03(\x01\x32Y\n\x0cMasterServer\x12I\n\x0fget_sensor_data\x12\x19.master_server.SensorName\x1a\x19.master_server.SensorData\"\x00\x62\x06proto3'
)




_SENSORNAME = _descriptor.Descriptor(
  name='SensorName',
  full_name='master_server.SensorName',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='master_server.SensorName.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=64,
)


_SENSORDATA = _descriptor.Descriptor(
  name='SensorData',
  full_name='master_server.SensorData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='master_server.SensorData.timestamp', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='row_number', full_name='master_server.SensorData.row_number', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='col_number', full_name='master_server.SensorData.col_number', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sensor_data', full_name='master_server.SensorData.sensor_data', index=3,
      number=4, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=158,
)

DESCRIPTOR.message_types_by_name['SensorName'] = _SENSORNAME
DESCRIPTOR.message_types_by_name['SensorData'] = _SENSORDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SensorName = _reflection.GeneratedProtocolMessageType('SensorName', (_message.Message,), {
  'DESCRIPTOR' : _SENSORNAME,
  '__module__' : 'master_server_pb2'
  # @@protoc_insertion_point(class_scope:master_server.SensorName)
  })
_sym_db.RegisterMessage(SensorName)

SensorData = _reflection.GeneratedProtocolMessageType('SensorData', (_message.Message,), {
  'DESCRIPTOR' : _SENSORDATA,
  '__module__' : 'master_server_pb2'
  # @@protoc_insertion_point(class_scope:master_server.SensorData)
  })
_sym_db.RegisterMessage(SensorData)



_MASTERSERVER = _descriptor.ServiceDescriptor(
  name='MasterServer',
  full_name='master_server.MasterServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=160,
  serialized_end=249,
  methods=[
  _descriptor.MethodDescriptor(
    name='get_sensor_data',
    full_name='master_server.MasterServer.get_sensor_data',
    index=0,
    containing_service=None,
    input_type=_SENSORNAME,
    output_type=_SENSORDATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MASTERSERVER)

DESCRIPTOR.services_by_name['MasterServer'] = _MASTERSERVER

# @@protoc_insertion_point(module_scope)
